name: Our CD

on:
  workflow_dispath:
    release:
      type:
        - published

jobs:
  dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build SDist and wheel
        run: pipx run build
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  publish:
    need: [dist]
    run-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == ''
    environment: 
      name: se-for-sci-example
      url: https://test.pypi.org/p/se-for-sci-example
    permissions: 
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
